# Docker Compose file 
version: "3.8"
services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:80"
  #   # depends_on:
  #   #   - backend
  #   networks:
  #     - app-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - app-network
  # crawler:
  #   build:
  #     context: ./crawler
  #     dockerfile: Dockerfile
  #   networks:
  #     - app-network
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - frontend
  #   networks:
  #     - app-network
networks:
  app-network:
    driver: bridge
volumes:
  static_volume: